name: CI
on: workflow_call
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v6
      - name: Starting Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm install

      - name: check lint
        run: npm run lint

      - name: build project
        run: npm run build

      - name: run project unit tests
        run: npm run test:unit
